name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: generate-snake-game
        uses: Platane/snk@v3
        with:
          github_user_name: tqha1011
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00FF00&color_dots=#161b22,#00441b,#006d2c,#238b45,#41ab5d
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      - name: push-to-output-branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          # Đảm bảo bạn đã tạo Secret tên là GH_TOKEN trong Settings
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
